# Travis CI Configuration File

# Tell Travis CI we're using PHP
language: php

# Versions of PHP to test against
php:
    - "5.2"
    - "5.3"
    - "5.4"

# Specify versions of WordPress to test against
# WP_VERSION = WordPress version number (use "master" for SVN trunk)
# WP_MULTISITE = whether to test multisite (use either "0" or "1")
env:
    - WP_VERSION=master WP_MULTISITE=0
    - WP_VERSION=3.7.1 WP_MULTISITE=0
    - WP_VERSION=3.6.1 WP_MULTISITE=0

# Grab the setup script and execute
before_script:
    - wget https://raw.github.com/jbrinley/wordpress-plugin-tests/setup/setup.sh
    - source setup.sh

script: phpunit --configuration tests/phpunit.xml

